language: elixir
elixir:
  - 1.9.1

env:
  - MIX_ENV=test

script:
  - mix do deps.get, compile, test --warnings-as-errors, coveralls.json
  - cd apps/cli
  - mix escript.build

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

branches:
  only:
    - master
